version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/code
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --reload
    depends_on:
      - redis
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    stdin_open: true
    tty: true
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    restart: always

  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
